# **Bonus Project:** Classifying NSL-KDD Dataset using DRL

Classify network traffic from the NSL-KDD dataset as normal (0) or anomalous (1) using Deep Reinforcement Learning (DRL).

A Deep Q-Network (DQN) will be used to train a reinforcement learning agent, which learns to classify traffic based on feedback from its actions.

The model's goal is to optimize its policy and accurately identify normal vs. attack traffic for intrusion detection.

## Exploring Phase

In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('KDD_Shuffled_Combined_Set.csv')

In [22]:
df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,http,SF,338,18918,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
1,0,tcp,http,SF,308,4336,0,0,0,0,...,255,1.00,0.00,0.02,0.03,0.00,0.00,0.00,0.00,0.0
2,0,tcp,smtp,SF,1064,338,0,0,0,0,...,198,0.80,0.04,0.01,0.01,0.00,0.00,0.00,0.00,0.0
3,0,tcp,smtp,SF,768,384,0,0,0,0,...,117,0.59,0.03,0.01,0.02,0.01,0.00,0.00,0.00,0.0
4,0,tcp,smtp,S0,0,0,0,0,0,0,...,118,0.39,0.05,0.02,0.02,0.02,0.02,0.01,0.01,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148511,0,tcp,echo,RSTO,0,0,0,0,0,0,...,4,0.02,0.09,0.00,0.00,0.00,0.00,1.00,1.00,1.0
148512,0,tcp,telnet,S0,0,0,0,0,0,0,...,4,0.02,0.07,0.01,0.00,1.00,1.00,0.00,0.00,1.0
148513,0,tcp,smtp,SF,0,83,0,0,0,0,...,124,0.49,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.0
148514,899,tcp,domain,RSTO,1562,0,0,0,0,0,...,2,1.00,0.00,0.50,0.00,0.00,0.00,1.00,1.00,1.0
148515,0,udp,domain_u,SF,43,70,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.0

In [23]:
df.isnull().sum()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [24]:
df.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
label                          float64
dtype: object

In [25]:
for col_name in ('label', 'protocol_type', 'service', 'flag'):
    unique = df[col_name].unique()
    print(col_name, '\t', len(unique), unique)
    print()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

label 	 2 [0. 1.]

protocol_type 	 3 ['tcp' 'udp' 'icmp']

service 	 70 ['http' 'smtp' 'domain_u' 'other' 'courier' 'private' 'ftp_data' 'telnet'
 'eco_i' 'link' 'auth' 'bgp' 'sql_net' 'whois' 'imap4' 'tftp_u' 'gopher'
 'ecr_i' 'netbios_ssn' 'Z39_50' 'X11' 'http_443' 'time' 'ftp' 'uucp_path'
 'pop_3' 'klogin' 'efs' 'discard' 'ssh' 'netbios_dgm' 'supdup' 'uucp'
 'login' 'urp_i' 'kshell' 'echo' 'finger' 'hostnames' 'netstat' 'domain'
 'nnsp' 'ldap' 'iso_tsap' 'ctf' 'pop_2' 'nntp' 'exec' 'daytime' 'vmnet'
 'csnet_ns' 'netbios_ns' 'systat' 'mtp' 'ntp_u' 'remote_job' 'name' 'IRC'
 'rje' 'urh_i' 'sunrpc' 'printer' 'red_i' 'shell' 'tim_i' 'aol' 'pm_dump'
 'harvest' 'http_2784' 'http_8001']

flag 	 11 ['SF' 'S0' 'REJ' 'RSTR' 'RSTO' 'S1' 'SH' 'S2' 'S3' 'OTH' 'RSTOS0']

## Preprocessing Phase

In [26]:

col_names = ['protocol_type', 'service', 'flag']

df_encoded = pd.get_dummies(df, columns=col_names)
df_encoded

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,338,18918,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,True,False
1,0,308,4336,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,True,False
2,0,1064,338,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,True,False
3,0,768,384,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,True,False
4,0,0,0,0,0,0,0,0,0,0,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148511,0,0,0,0,0,0,0,0,0,0,...,False,True,False,False,False,False,False,False,False,False
148512,0,0,0,0,0,0,0,0,0,0,...,False,False,False,False,True,False,False,False,False,False
148513,0,0,83,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,True,False
148514,899,1562,0,0,0,0,0,0,0,0,...,False,True,False,False,False,False,False,False,False,False
148515,0,43,70,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,True,False

In [27]:
df_encoded.dtypes

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

duration          int64
src_bytes         int64
dst_bytes         int64
land              int64
wrong_fragment    int64
                  ...
flag_S1            bool
flag_S2            bool
flag_S3            bool
flag_SF            bool
flag_SH            bool
Length: 123, dtype: object

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_encoded), columns=df_encoded.columns)
df_scaled['label'] = df_encoded['label']
df_scaled['label']

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
148511    1.0
148512    1.0
148513    0.0
148514    1.0
148515    0.0
Name: label, Length: 148516, dtype: float64

In [29]:
from sklearn.model_selection import train_test_split

X = df_scaled.drop('label', axis=1)
y = df_scaled['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

## Creating Environment

In [30]:
import gym
from gym import spaces
import random

class NSLKDDEnv(gym.Env):
    def __init__(self, X, y):
        super(NSLKDDEnv, self).__init__()

        # Attached dataset can be test or train depending on the phase
        self.X = X.reset_index(drop=True)
        self.y = y.reset_index(drop=True)

        # Initial State
        self.reset()

        # Actions are Normal and Anomaly
        self.action_space = spaces.Discrete(2)

        # Space is simply the features
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(self.X.shape[1],), dtype=np.float32)

    def reset(self):
        # Randomly select any row from the linked dataset
        self.loc = 0
        self.perc = 0.0
        self.state = self.X.loc[self.loc]
        return self.state

    def step(self, action):
        # Postive reward if correct action
        # Negative reward if wrong action
        reward = 1 if action == self.y.loc[self.loc] else -1

        # Next location
        self.loc += 1
        self.perc = self.loc / self.X.shape[0]

        # Done if there is no more remaining locations
        done = True
        if self.loc < self.X.shape[0]:
            self.state = self.X.loc[self.loc]
            done = False

        return self.state, reward, done, {}

    def render(self):
        print(f'NSLKDDEnv at {self.perc:%} of steps')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [31]:
env = NSLKDDEnv(X_train, y_train)

state = env.reset()
done = False
score = 0
while not done:
    action = env.action_space.sample()  # Random action (select feature index)
    new_state, reward, done, _ = env.step(action)
    score += reward
    print(f'Score: {score}', end='\t')
    env.render()
    state = new_state
    if env.loc == 10:
        break

Score: -1	NSLKDDEnv at 0.000842% of steps
Score: -2	NSLKDDEnv at 0.001683% of steps
Score: -3	NSLKDDEnv at 0.002525% of steps
Score: -2	NSLKDDEnv at 0.003367% of steps
Score: -3	NSLKDDEnv at 0.004208% of steps
Score: -2	NSLKDDEnv at 0.005050% of steps
Score: -1	NSLKDDEnv at 0.005892% of steps
Score: 0	NSLKDDEnv at 0.006733% of steps
Score: -1	NSLKDDEnv at 0.007575% of steps
Score: -2	NSLKDDEnv at 0.008417% of steps

## Training Phase, DRL Model

In [32]:
import tensorflow as tf
from tensorflow.keras import models, layers, optimizers

In [33]:
input_shape = env.observation_space.shape[0]
num_actions = env.action_space.n
input_shape, num_actions

(122, 2)

In [34]:
!pip install stable-baselines3 torch shimmy

Requirement already satisfied: stable-baselines3 in /usr/local/lib/python3.10/dist-packages (2.4.0)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: shimmy in /usr/local/lib/python3.10/dist-packages (2.0.0)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3) (1.0.0)
Requirement already satisfied: numpy<2.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3) (1.26.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from stable-baselines3) (3.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from stable-baselines3) (3.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->stable-baselines3) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->stable-baselines3) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.17.0)

In [35]:
from stable_baselines3 import PPO

env = NSLKDDEnv(X_train, y_train)
model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=1000000)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(

-----------------------------
| time/              |      |
|    fps             | 364  |
|    iterations      | 1    |
|    time_elapsed    | 5    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 303         |
|    iterations           | 2           |
|    time_elapsed         | 13          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.018240504 |
|    clip_fraction        | 0.376       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.678      |
|    explained_variance   | -0.0274     |
|    learning_rate        | 0.0003      |
|    loss                 | 3.4         |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0483     |
|    value_loss           | 7.21        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 273         |
|    iterations           | 3           |
|    time_elapsed         | 22          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.020984832 |
|    clip_fraction        | 0.346       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.624      |
|    explained_variance   | -0.0185     |
|    learning_rate        | 0.0003      |
|    loss                 | 4.35        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0452     |
|    value_loss           | 9.16        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 303         |
|    iterations           | 4           |
|    time_elapsed         | 27          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.023838017 |
|    clip_fraction        | 0.237       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.549      |
|    explained_variance   | -0.0816     |
|    learning_rate        | 0.0003      |
|    loss                 | 3.83        |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0385     |
|    value_loss           | 12.5        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 315         |
|    iterations           | 5           |
|    time_elapsed         | 32          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.019206408 |
|    clip_fraction        | 0.158       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.465      |
|    explained_variance   | -0.133      |
|    learning_rate        | 0.0003      |
|    loss                 | 3.07        |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0299     |
|    value_loss           | 14.8        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 330         |
|    iterations           | 6           |
|    time_elapsed         | 37          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.024411395 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.38       |
|    explained_variance   | -0.558      |
|    learning_rate        | 0.0003      |
|    loss                 | 3.47        |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0242     |
|    value_loss           | 21.8        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 341         |
|    iterations           | 7           |
|    time_elapsed         | 42          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.007227164 |
|    clip_fraction        | 0.0591      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.286      |
|    explained_variance   | -0.368      |
|    learning_rate        | 0.0003      |
|    loss                 | 2.07        |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0151     |
|    value_loss           | 29.7        |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 352          |
|    iterations           | 8            |
|    time_elapsed         | 46           |
|    total_timesteps      | 16384        |
| train/                  |              |
|    approx_kl            | 0.0033384652 |
|    clip_fraction        | 0.0406       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.221       |
|    explained_variance   | -1.02        |
|    learning_rate        | 0.0003       |
|    loss                 | 40           |
|    n_updates            | 70           |
|    policy_gradient_loss | -0.0116      |
|    value_loss           | 32.1         |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 362         |
|    iterations           | 9           |
|    time_elapsed         | 50          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.004163322 |
|    clip_fraction        | 0.036       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.181      |
|    explained_variance   | -2.35       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.48        |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0123     |
|    value_loss           | 32.9        |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 366          |
|    iterations           | 10           |
|    time_elapsed         | 55           |
|    total_timesteps      | 20480        |
| train/                  |              |
|    approx_kl            | 0.0036531873 |
|    clip_fraction        | 0.0305       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.139       |
|    explained_variance   | -4.93        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.31         |
|    n_updates            | 90           |
|    policy_gradient_loss | -0.00933     |
|    value_loss           | 32.5         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 373          |
|    iterations           | 11           |
|    time_elapsed         | 60           |
|    total_timesteps      | 22528        |
| train/                  |              |
|    approx_kl            | 0.0053781103 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.109       |
|    explained_variance   | -3.57        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.55         |
|    n_updates            | 100          |
|    policy_gradient_loss | -0.00577     |
|    value_loss           | 22.2         |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 380         |
|    iterations           | 12          |
|    time_elapsed         | 64          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.015430785 |
|    clip_fraction        | 0.0269      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.0885     |
|    explained_variance   | -0.266      |
|    learning_rate        | 0.0003      |
|    loss                 | 1.15        |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00467    |
|    value_loss           | 10.3        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 382         |
|    iterations           | 13          |
|    time_elapsed         | 69          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.008938417 |
|    clip_fraction        | 0.0223      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.0577     |
|    explained_variance   | -3.09       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.08        |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00469    |
|    value_loss           | 14.5        |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 387          |
|    iterations           | 14           |
|    time_elapsed         | 74           |
|    total_timesteps      | 28672        |
| train/                  |              |
|    approx_kl            | 0.0022363602 |
|    clip_fraction        | 0.00913      |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0403      |
|    explained_variance   | -7.5         |
|    learning_rate        | 0.0003       |
|    loss                 | 0.783        |
|    n_updates            | 130          |
|    policy_gradient_loss | -0.00133     |
|    value_loss           | 17.3         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 391          |
|    iterations           | 15           |
|    time_elapsed         | 78           |
|    total_timesteps      | 30720        |
| train/                  |              |
|    approx_kl            | 0.0022051735 |
|    clip_fraction        | 0.0123       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.044       |
|    explained_variance   | -10.2        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.02         |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.00273     |
|    value_loss           | 24.4         |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 392         |
|    iterations           | 16          |
|    time_elapsed         | 83          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.005130887 |
|    clip_fraction        | 0.0146      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.038      |
|    explained_variance   | -11.1       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.14        |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00272    |
|    value_loss           | 30.9        |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 396        |
|    iterations           | 17         |
|    time_elapsed         | 87         |
|    total_timesteps      | 34816      |
| train/                  |            |
|    approx_kl            | 0.00820205 |
|    clip_fraction        | 0.0201     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.0337    |
|    explained_variance   | -16.3      |
|    learning_rate        | 0.0003     |
|    loss                 | 371        |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.00393   |
|    value_loss           | 37         |
----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 398          |
|    iterations           | 18           |
|    time_elapsed         | 92           |
|    total_timesteps      | 36864        |
| train/                  |              |
|    approx_kl            | 0.0039124745 |
|    clip_fraction        | 0.0109       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0298      |
|    explained_variance   | -4.49        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.479        |
|    n_updates            | 170          |
|    policy_gradient_loss | -0.00168     |
|    value_loss           | 5.98         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 400          |
|    iterations           | 19           |
|    time_elapsed         | 97           |
|    total_timesteps      | 38912        |
| train/                  |              |
|    approx_kl            | 0.0031196643 |
|    clip_fraction        | 0.0102       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0236      |
|    explained_variance   | -17.2        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.915        |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.00212     |
|    value_loss           | 41.3         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 403          |
|    iterations           | 20           |
|    time_elapsed         | 101          |
|    total_timesteps      | 40960        |
| train/                  |              |
|    approx_kl            | 0.0027658525 |
|    clip_fraction        | 0.0144       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0272      |
|    explained_variance   | -12.6        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.44         |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.00267     |
|    value_loss           | 18.6         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 403          |
|    iterations           | 21           |
|    time_elapsed         | 106          |
|    total_timesteps      | 43008        |
| train/                  |              |
|    approx_kl            | 0.0040694843 |
|    clip_fraction        | 0.0146       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0256      |
|    explained_variance   | -10.1        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.804        |
|    n_updates            | 200          |
|    policy_gradient_loss | -0.00256     |
|    value_loss           | 15.4         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 405          |
|    iterations           | 22           |
|    time_elapsed         | 111          |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0036866835 |
|    clip_fraction        | 0.015        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0262      |
|    explained_variance   | -7.04        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.83         |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.00275     |
|    value_loss           | 15.8         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 407          |
|    iterations           | 23           |
|    time_elapsed         | 115          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0023967088 |
|    clip_fraction        | 0.0121       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0242      |
|    explained_variance   | -8.84        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.653        |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.0029      |
|    value_loss           | 16           |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 407         |
|    iterations           | 24          |
|    time_elapsed         | 120         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.006522166 |
|    clip_fraction        | 0.0233      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.0225     |
|    explained_variance   | -7.93       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.01        |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00491    |
|    value_loss           | 16.7        |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 409          |
|    iterations           | 25           |
|    time_elapsed         | 124          |
|    total_timesteps      | 51200        |
| train/                  |              |
|    approx_kl            | 0.0059241927 |
|    clip_fraction        | 0.0165       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0237      |
|    explained_variance   | -8.75        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.579        |
|    n_updates            | 240          |
|    policy_gradient_loss | -0.00223     |
|    value_loss           | 16.3         |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 411          |
|    iterations           | 26           |
|    time_elapsed         | 129          |
|    total_timesteps      | 53248        |
| train/                  |              |
|    approx_kl            | 0.0038171983 |
|    clip_fraction        | 0.0115       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.0182      |
|    explained_variance   | -0.052       |
|    learning_rate        | 0.0003       |
|    loss                 | 0.603        |
|    n_updates            | 250          |
|    policy_gradient_loss | -0.00205     |
|    value_loss           | 1.17         |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 411         |
|    iterations           | 27          |
|    time_elapsed         | 134         |
|    total_timesteps      | 55296       |
| train/                  |             |
|    approx_kl            | 0.005918951 |
|    clip_fraction        | 0.0186      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.0239     |
|    explained_variance   | -13.6       |
|    learning_rate        | 0.0003      |
|    loss                 | 1.25        |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.00273    |

KeyboardInterrupt:

In [36]:
model.save("drl_model")

In [41]:
from sklearn.metrics import accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score, matthews_corrcoef

model = PPO.load("drl_model")

# Evaluate the agent
envs = {'train': NSLKDDEnv(X_train, y_train), 'test': NSLKDDEnv(X_test, y_test)}
for phase in ['train', 'test']:
    print(f"\n\nEvaluating {phase} phase...")

    env = envs[phase]
    obs = env.reset()
    done = False
    total_rewards = 0
    predicted_labels = []
    true_labels = env.y
    pred = []

    while not done:
        action, _state = model.predict(obs)
        obs, reward, done, info = env.step(action)
        total_rewards += reward
        predicted_labels.append(action)
        perc = env.perc * 100
        if perc > 0 and perc % 5 == 0:
          env.render()

    print(f"Total rewards for {phase} phase: {total_rewards}")

    accuracy = accuracy_score(true_labels, predicted_labels)
    balanced_accuracy = balanced_accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, zero_division=1)
    recall = recall_score(true_labels, predicted_labels, zero_division=1)
    f1 = f1_score(true_labels, predicted_labels, zero_division=1)
    mcc = matthews_corrcoef(true_labels, predicted_labels)

    # Print metrics
    print("Evaluation Metrics:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Balanced Accuracy: {balanced_accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"Matthews Correlation Coefficient (MCC): {mcc:.4f}")


    env.close()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(

Evaluating train phase...
NSLKDDEnv at 25.000000% of steps
NSLKDDEnv at 50.000000% of steps
NSLKDDEnv at 75.000000% of steps
NSLKDDEnv at 100.000000% of steps
Total rewards for train phase: 111794
Evaluation Metrics:
Accuracy: 0.9705
Balanced Accuracy: 0.9702
Precision: 0.9757
Recall: 0.9625
F1-Score: 0.9691
Matthews Correlation Coefficient (MCC): 0.9409


Evaluating test phase...
NSLKDDEnv at 25.000000% of steps
NSLKDDEnv at 50.000000% of steps
NSLKDDEnv at 75.000000% of steps
NSLKDDEnv at 100.000000% of steps
Total rewards for test phase: 27912
Evaluation Metrics:
Accuracy: 0.9698
Balanced Accuracy: 0.9696
Precision: 0.9753
Recall: 0.9620
F1-Score: 0.9686
Matthews Correlation Coefficient (MCC): 0.9397

### Train Phase
| Metric                           | Value       |
|----------------------------------|-------------|
| Total Rewards                    | 111794      |
| Accuracy                         | 0.9705      |
| Balanced Accuracy                | 0.9702      |
| Precision                        | 0.9757      |
| Recall                           | 0.9625      |
| F1-Score                         | 0.9691      |
| Matthews Correlation Coefficient (MCC) | 0.9409  |

### Test Phase
| Metric                           | Value       |
|----------------------------------|-------------|
| Total Rewards                    | 27912       |
| Accuracy                         | 0.9698      |
| Balanced Accuracy                | 0.9696      |
| Precision                        | 0.9753      |
| Recall                           | 0.9620      |
| F1-Score                         | 0.9686      |
| Matthews Correlation Coefficient (MCC) | 0.9397  |